apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      {{- if .Values.affinity }}
      affinity:
      {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}

      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "app.serviceaccountname" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.persistence.enabled }}
      volumes:
        - name: duckdb
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-pvc" (include "app.name" .)) .Values.persistence.existingClaim | quote }}
      {{- end }}

      containers:
        - name: predictive-hpa
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" | quote }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

          envFrom:
            - configMapRef:
                name: {{ include "app.name" $ }}-configmap

          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: duckdb
          {{- end }}
