apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "app.name" . }}-scaler
  labels:
    {{- include "app.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]